include:
  - path: infra/compose/docker-compose.infra.yml
  - path: infra/compose/docker-compose.migrate.yml
  - path: infra/compose/docker-compose.services.yml
  - path: infra/compose/docker-compose.web.yml
