apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "your_postgres_password"
  REDIS_PASSWORD: "your_redis_password"
  SECURITY_USER: "admin"
  SECURITY_PASSWORD: "your_admin_password"
  JWT_SECRET: "your_jwt_secret_key_at_least_256_bits"
  GOOGLE_CLIENT_ID: "your_google_client_id.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
  MAIL_USERNAME: "noreply@example.com"
  MAIL_PASSWORD: "your_mail_password"
  S3_USER: "minioadmin"
  S3_PASSWORD: "your_minio_password"
