server:
  port: 8084

spring:
  application:
    name: notification-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

app:
  frontend:
    url: ${FRONTEND_URL}
  kafka:
    topics:
      user-registered: user-registered-topic
      verification-email: verification-email-topic
      password-reset-email: password-reset-email-topic
    consumer:
      notification-group: notification-group
      dlt-group: notification-dlt-group

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: "http://zipkin:9411/api/v2/spans"